src/commands/create-expo-stack.ts

Support various package managers

---

cli/__tests__/cli-integration.test.ts
cli/src/commands/create-expo-stack.ts
cli/src/templates/base/babel.config.js.ejs
cli/src/templates/base/package.json.ejs
cli/src/templates/packages/expo-router/drawer/app/(drawer)/_layout.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/(drawer)/index.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/(drawer)/news.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/_layout.tsx.ejs
cli/src/templates/packages/react-navigation/navigation/drawer-navigator.tsx.ejs
cli/src/templates/packages/react-navigation/navigation/index.tsx.ejs
cli/src/types.ts
cli/src/utilities/configureProjectFiles.ts
cli/src/utilities/generateProjectFiles.ts
cli/src/utilities/runCLI.ts

Allow Drawer navigation (side menu) next to tabs and stack layout for both Expo Router and React Navigation.

Add Drawer Navigator (Expo Router + React Navigation)

---

docs/src/components/Icons/GitHubIcon.astro
docs/src/components/RightSidebar/MoreMenu.astro
docs/src/components/Seo/HeadCommon.astro
www/astro.config.mjs
www/src/components/landing/contributors/contributor.tsx
www/src/components/landing/contributors/contributorsSection.tsx
www/src/components/landing/footer/footer.astro
www/src/components/landing/navbar/githubStarButton.astro
www/src/components/landing/navbar/navbar.astro
www/src/components/landing/stack/expoRouter.astro
www/src/components/landing/stack/firebase.astro
www/src/components/landing/stack/nativeWind.astro
www/src/components/landing/stack/reactNavigation.astro
www/src/components/landing/stack/supabase.astro
www/src/components/landing/stack/tamagui.astro
www/src/components/landing/stack/typeScript.astro
www/src/components/seo/headCommon.astro
www/src/pages/discord.astro

- Added in noreferrer noopener
- Added discord mobile view icon  to footer 
- Made expostack.dev/discord redirect

Updated links and added discord mobile social icon

---

cli/__tests__/cli-integration.test.ts
contributing.md

- Various updates to the contributing.md file I noticed were necessary while setting up my environments
- one "fix" to the cli tests: although they are still not working, this removes the first issue...

contributing.md Updates

---

.changeset/afraid-carrots-tease.md
cli/src/templates/packages/expo-router/tabs/app/_layout.tsx.ejs

fix(cli): tabs dupe import

---

.changeset/tidy-teachers-join.md
cli/src/templates/base/package.json.ejs

Rebased and added a changeset/patch notes for #72 -- see the original PR for more details.

fixed format error while running format script (rebased)

---

.github/workflows/run-tests.yaml
cli/__tests__/cli-integration.test.ts
cli/package.json

- Phase 1 of #18 
- Fixes `bun run test` script to execute
- Adds starter CI to build cli and run tests for a feature branch

chore: improve tests phase 1 

---

www/src/components/landing/footer/footer.astro

[www] add footer callout for Expo trademark

---

cli/src/utilities/getPackageManager.ts
docs/astro.config.mjs
docs/package.json
docs/pnpm-lock.yaml
docs/src/components/RightSidebar/MoreMenu.astro
docs/src/components/Seo/HeadSEO.astro
docs/src/content/docs/en/folder-structure.mdx
docs/src/layouts/MainLayout.astro

- Removed t3 references 
- Updated site url from expostack.dev to createexpostack.com 
- Added astro vercel to package.json
- Removed unused commented code
- Updated header title 
- Commented out Analytics, currently is giving a warning 
- Added the pnpm lock file

Made updates to the docs

---

.changeset/happy-peaches-watch.md
.changeset/honest-starfishes-begin.md
cli/src/commands/create-expo-stack.ts
cli/src/utilities/runCLI.ts

Sometime the package manager comes back undefined which causes the app to break on certain conditions

[cli] Fix some package manager being undefined stuff

---

.changeset/strange-olives-study.md
cli/src/utilities/generateProjectFiles.ts

implemented proposed fix from #131

[cli,bug] moved the addition of the project name (#131)

---

.changeset/stale-suns-remember.md
cli/src/templates/packages/firebase/metro.config.js
cli/src/templates/packages/firebase/metro.config.js.ejs
cli/src/utilities/configureProjectFiles.ts

based on #127 (different account, same person 👋 )
tested with the following commands:
`create-expo-stack test-repo-fire --stylesheet --importAlias --firebase --yarn`
`create-expo-stack test-repo-expo-router --expo-router --stylesheet --importAlias --yarn`
`create-expo-stack test-repo-both --expo-router --stylesheet --importAlias --firebase --yarn`

[cli] updated the metro.config of the firebase package to take expo-router into account

---

www/src/components/landing/hero/copyCommandButton.tsx

rounded-md wasn't working because shadcn has a custom config of it in the tailwind.config.mjs file. So I had to set it like this rounded-[6px] for it to show.

Added back round corners to copy command button

---

contributing.md

add note about bun version upgrade in the event that trying to commit changes leads to an error regarding the `lint-staged` script missing
https://discord.com/channels/1173879003191459860/1175505640156844084/1188627094893236285

[docs] Update contributing.md

---

.changeset/twelve-flies-lay.md
cli/src/templates/packages/expo-router/stack/app/_layout.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/details.tsx.ejs
cli/src/templates/packages/tamagui/tamagui.config.ts.ejs

This is a replacement for https://github.com/danstepanov/create-expo-stack/pull/161

[cli] fix font default styles on expo router tamagui stack template

---

www/src/components/landing/hero/cliDemo.tsx
www/src/components/landing/stack/expoRouter.astro
www/src/components/landing/stack/firebase.astro
www/src/components/landing/stack/nativeWind.astro
www/src/components/landing/stack/reactNavigation.astro
www/src/components/landing/stack/stackSection.astro
www/src/components/landing/stack/supabase.astro
www/src/components/landing/stack/tamagui.astro
www/src/components/landing/stack/typeScript.astro

before
after
before
https://github.com/danstepanov/create-expo-stack/assets/31113245/9fd7dfcf-e476-47f7-b0a3-26a1877727e4
after
https://github.com/danstepanov/create-expo-stack/assets/31113245/4ed435a3-e46e-4026-8919-e2cbdb651cff

landing fixes

---

www/src/components/landing/hero/heroSection.astro
www/src/styles/globals.css

https://github.com/danstepanov/create-expo-stack/assets/31113245/179f5c18-3c50-44a7-886b-67aaeb20f0c2

reduce flickerness on hero title

---

www/src/components/landing/stack/unistyles.astro

https://github.com/danstepanov/create-expo-stack/assets/31113245/0892963f-8210-455f-80da-659a47d3faf6

Feature unistyles template

---

.changeset/quick-bobcats-clap.md
cli/src/templates/packages/expo-router/drawer/app/(drawer)/index.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/(drawer)/news.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/[...unmatched].tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/_layout.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/[...unmatched].tsx.ejs
cli/src/templates/packages/expo-router/stack/app/_layout.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/details.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/index.tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/(tabs)/_layout.tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/(tabs)/index.tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/(tabs)/two.tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/[...unmatched].tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/_layout.tsx.ejs
cli/src/templates/packages/expo-router/tabs/app/modal.tsx.ejs
cli/src/templates/packages/expo-router/tabs/components/edit-screen-info.tsx.ejs
cli/src/templates/packages/react-navigation/App.tsx.ejs
cli/src/templates/packages/react-navigation/components/edit-screen-info.tsx.ejs
cli/src/templates/packages/react-navigation/navigation/index.tsx.ejs
cli/src/templates/packages/react-navigation/navigation/tab-navigator.tsx.ejs
cli/src/templates/packages/react-navigation/screens/details.tsx.ejs
cli/src/templates/packages/react-navigation/screens/modal.tsx.ejs
cli/src/templates/packages/react-navigation/screens/one.tsx.ejs
cli/src/templates/packages/react-navigation/screens/overview.tsx.ejs
cli/src/templates/packages/react-navigation/screens/two.tsx.ejs
cli/src/templates/packages/unistyles/theme.ts.ejs
cli/src/templates/packages/unistyles/unistyles.ts.ejs

- Add components to the unistyles theme that can be reused by each template
- Add missing unistyles registry import

[cli] Setup Unistyles theme

---

.changeset/lovely-dingos-approve.md
cli/src/templates/packages/react-navigation/navigation/drawer-navigator.tsx.ejs
cli/src/templates/packages/react-navigation/navigation/tab-navigator.tsx.ejs

Drawer+Tabs react navigation option: Fix typescript

---

www/src/components/landing/stack/expoRouter.astro
www/src/components/landing/stack/nativeWind.astro
www/src/layouts/landingPage.astro

bump versions on landing

---

docs/src/content/docs/en/installation.md

Removed duplicate flag [docs]
I removed a duplicate description of what `--stylesheet` does.
Clarity
Have not been tested.

[docs] Remove duplicate description

---

cli/src/utilities/showHelp.ts

Resolve a wording issue in the show help.

[CLI]: mistake for i18n in the show help

---

cli/src/templates/packages/nativewind/components/Button.tsx.ejs

I added the props from base example to fix a type error
Just removes some initial friction with the nativewind template
added these to my own project initialised with create expo stack

fix: missing button props when using nativewind

---

cli/src/templates/packages/nativewindui/tailwind.config.js.ejs

Update the `tailwind.config.js` file for the NativeWindUI template's css variables to accept an opacity value
Work around for NativeWind bug: https://github.com/marklawlor/nativewind/issues/859
Locally with bun.

[cli] enable nativewind-ui css variables to accept an opacity value

---

cli/src/templates/packages/nativewindui/app/index.tsx.ejs

[cli] nativewind-ui center empty list content

---

cli/src/templates/base/package.json.ejs

Updates @roninoss/icons to latest version.
Locally with bun on ios

[cli] nw-ui update ronin/icons to latest

---

cli/src/templates/base/package.json.ejs
cli/src/utilities/printOutput.ts

Updates eslint and hides the output except for errors
During the generation of a new project you get a bunch of output from eslint and prettier that you probably don't need to see
been testing it locally
before:
after

feat: update eslint and hide stdout

---

.changeset/quick-pens-yawn.md
cli/src/utilities/printOutput.ts

Installs expo@latest and then runs expo install --fix immediately after to make sure we have the latest compatible versions of everything. 
This reduces the need to manually update package versions.

feat: always use latest expo and update packages

---

.changeset/rich-poems-sing.md
cli/src/templates/base/package.json.ejs

Add prebuild script to nativewindui

---

cli/src/templates/packages/expo-router/drawer/app/(drawer)/(tabs)/_layout.tsx.ejs
cli/src/templates/packages/expo-router/drawer/app/(drawer)/index.tsx.ejs

This PR addresses a typo in the path specified in the index file. The incorrect path could potentially lead to module resolution errors. Additionally, this PR also removes unnecessary imports that were identified in the codebase. These changes aim to improve the readability and efficiency of the code.
The motivation behind these changes is to enhance the code quality by removing unnecessary imports and ensuring all paths are correctly specified. This contributes to better maintainability and less confusion for future contributors.
The changes have been tested locally to ensure that the removal of imports and the correction of the path does not affect the functionality of the code.

fix(drawer): Corrected Path Typo in Index File and Removed Unnecessary Imports

---

www/src/layouts/landingPage.astro
www/src/styles/globals.css

fixes #317 and overflow-x on FF

---

.changeset/happy-rings-judge.md
cli/src/templates/base/components/Button.tsx.ejs
cli/src/templates/packages/nativewind/components/Button.tsx.ejs
cli/src/templates/packages/nativewindui/components/Button.tsx.ejs
cli/src/templates/packages/restyle/components/Button.tsx.ejs
cli/src/templates/packages/unistyles/components/Button.tsx.ejs

Pass down the props from the `components/Button` to the `TouchableOpacity` component. This allows us to send any touchable component props to the `<Button />` component, and they will work. 
This PR should also fix some issues and inconsistencies:
- ref prop was not always attached to the touchable
- `ButtonProps` was missing for some buttons
The button from tamagui template is fixed in a separate PR: https://github.com/danstepanov/create-expo-stack/pull/328
Also, it merges the styles from the props with the default styles, allowing us to override specific style properties.
I used create-expo-stack, and had to send some custom props to the Button such as `onLongPress`. For that, I had to go into the button and edit it to pass it down to the Touchable.
I generated a new project for all the …

[cli] Pass down props for button components

---

.changeset/strong-spies-sort.md
cli/__tests__/__snapshots__/cli-integration.test.ts.snap
cli/__tests__/cli-integration.test.ts

removes versions from snapshot checks so we primary just check which packages are installed and not the versions. this reduces the need for updating snapshots

fix: remove versions from snapshot

---

cli/src/templates/base/package.json.ejs
cli/src/templates/packages/supabase/utils/supabase.ts.ejs

This pr removes the URL polyfill as it's built-in in expo now
Check https://docs.expo.dev/versions/latest/sdk/url/ for more info

[cli] chore: remove url polyfill

---

.changeset/cold-dingos-smell.md
cli/src/templates/base/app.json.ejs

Upgrade  launchModeExperimental to use stable launchMode property in app.json.ejs 
Just house keeping to ensure repo is up to date
It's a non breaking change

[cli] Upgrade launchModeExperimental to use estable launchMode

---

.changeset/nervous-icons-walk.md
cli/src/templates/packages/nativewindui/drawer/app/_layout.tsx.ejs
cli/src/templates/packages/nativewindui/stack/app/_layout.tsx.ejs
cli/src/templates/packages/nativewindui/tabs/app/_layout.tsx.ejs
cli/src/types.ts
cli/src/utilities/configAnalytics.ts
cli/src/utilities/configStorage.ts
cli/src/utilities/configureProjectFiles.ts

fixes new configs not being stored and adds example providers
running it locally

fix: config not being stored and track analytics package installs

---

.changeset/poor-dots-decide.md
cli/src/templates/packages/nativewindui/components/nativewindui/Avatar.tsx.ejs

CES implementation of the following change https://github.com/roninoss/nativewindui/pull/11

[cli] show avatar fallback if no avatar image is provided, fix RON-150

---

.changeset/cool-cooks-reply.md
cli/src/templates/packages/nativewind/tailwind.config.js.ejs

this is my first time contributing to open source so feel free to correct my mistakes and guide me
added compoents diretory to tailwind config
styles dont work 
tailwind wont see the styles in component folder
using the cli locally and verifying that styles do work when running the project

Add missing components directory to tailwind config

---

cli/src/templates/packages/react-navigation/screens/details.tsx.ejs

This PR is for a Typo fix in `details.tsx.ejs` screen
none
typo issue in page, my spell check extension was throwing error because of this typo
its a typo change, should not affect anything functionally
none typo change

Typofix: typo fix in details.tsx.ejs screen

---

.changeset/long-coats-call.md
cli/src/templates/base/package.json.ejs

fix: nwui failing by updating some versions

---

.changeset/unlucky-guests-admire.md
cli/__tests__/__snapshots__/cli-integration.test.ts.snap
cli/src/templates/base/package.json.ejs

This fixes issues with the tamagui template by updating to the latest versions across the board and adding a missing dependency.
#453 
user reported an issue with the tamagui template
ran this locally and app opens after making these changes

fix: tamagui template

---

cli/src/templates/base/package.json.ejs

Upgrade Unistyles to latest beta!

feat: upgrade Unistyles to beta.8

---

.changeset/seven-ants-eat.md
cli/src/commands/create-expo-stack.ts
cli/src/utilities/index.ts
cli/src/utilities/publishToGitHub.ts
cli/src/utilities/showHelp.ts

This allows users to publish their repo created with create expo stack to Github. It returns a url for the repo upon completion.
A lot of people use this to reproduce issues and I want a fast way to share the repos.

add publish command

---

cli/src/templates/base/package.json.ejs

Upgrade Unistyles and it's dependencies from beta to RC2

chore: upgrade unistyles to rc2

---

README.md
cli/README.md
www/src/components/landing/stack/expoRouter.astro
www/src/components/landing/stack/reactNavigation.astro

updated the versions where I could find them

fix: update readme and website versions

---

cli/src/templates/base/package.json.ejs

Upgrade Unistyles from `rc.2` to `rc.4`!

feat: update unistyles to rc4

---

.changeset/angry-cycles-marry.md
cli/src/templates/base/components/Button.tsx.ejs
cli/src/templates/base/components/Container.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/details.tsx.ejs
cli/src/templates/packages/expo-router/stack/app/index.tsx.ejs
cli/src/templates/packages/nativewindui/components/Container.tsx.ejs

Add expo router support for stack templates using expo sdk 54
https://github.com/roninoss/create-expo-stack/pull/557
`bun run test`
and
1. `bun run dev myTestProject --expo-router --nativewind --overwrite`
2. `bun run dev myTestProject --expo-router --overwrite`

Expo Router support

---

.changeset/silver-trees-ask.md
cli/__tests__/cli-integration.test.ts
cli/src/templates/base/package.json.ejs
cli/src/templates/packages/nativewindui/stack/app/_layout.tsx.ejs
cli/src/templates/packages/nativewindui/stack/app/index.tsx.ejs
cli/src/templates/packages/nativewindui/stack/app/modal.tsx.ejs

update nativewindui templates to support sdk 54
