roninoss/create-expo-stack

src/commands/create-expo-stack.ts
`availablePackages` wasn't using `as const` which caused the below type to be an array of strings vs the values in the tuple
```ts
name: (typeof availablePackages)[number]; // string[]
```
=> fix: types 

src/utilities/runIgnite.ts
- Fixes cli input to Ignite, removes some `undefined` string that got carried on into the name and project directory
- Forwards on the user's package manager choice from `create-expo-stack`
`create-expo-stack CesIgnite2 --npm --ignite`
`create-expo-stack CesIgnite --yarn --ignite`
=> fix(run-ignite): defaults and forward pkg mgr

cli/src/utilities/configureProjectFiles.ts, cli/src/utilities/copyBaseAssets.ts, cli/src/utilities/printOutput.ts
Fixes: #30
The reason what that `toolbox.template.generate` was meant to be used with `.ejs`.
=> Split copying assets into a separate task

cli/src/templates/base/package.json.ejs
Fixes #38
Tested locally - hot reloading works correctly on web after this update.
=> Add react-refresh to overrides.

cli/src/templates/packages/tamagui/tamagui.config.ts.ejs
When using the tamagui + expo router template, I noticed that shorthand props like `jc="center"` weren't being auto-suggested or auto-completed. This change fixes that, but let me know if there's a reason it was left out in the first place. 
Here's the section of the docs that references this: https://tamagui.dev/docs/core/configuration
=> Fix: Added declare module type for shorthand props

cli/src/utilities/runIgnite.ts
- Ignite v9 was released, so this removes the version switch logic that was due to bun support not being available in v8
=> fix(run-ignite): no longer need the version check

cli/src/templates/base/App.tsx.ejs
My best guess is that EJS was silently omitting these in output. Remove them to avoid confusion.
=> chore(cli): templates/base/App.tsx.ejs: remove superfluous EJS brackets

.changeset/config.json, .changeset/tiny-penguins-join.md
fix .changeset/config.json ignore to refer to (valid) non-cli subprojects
This fixes the ability to run `bunx changeset`.
Thanks to @ernestoresende for providing the fix/instructions here!
=> chore: fix .changeset/config.json ignore

.changeset/famous-panthers-press.md, cli/src/commands/create-expo-stack.ts, cli/src/templates/base/app.json.ejs, cli/src/templates/base/tsconfig.json.ejs, cli/src/utilities/showHelp.ts, contributing.md, docs/src/content/docs/en/installation.md
- Closes #17 
- Adds `--importAlias` as a cli switch
- Will utilize default `~/*` mapped to `src` if no specific one is entered
- Can utilize other patterns, such as Expo's default `@/*` for example
- Validation when a string is passed in to make sure the format is correct
> Example of having a `Header` component live in `src/components/Header.tsx` and being imported via path alias: `import { Header } from '~/components/Header';`
=> feat(cli): adds `--importAlias`

cli/README.md
Add a newline to the README. The header text was not formatted correctly
=> docs: add newline

.changeset/config.json
This fixes an issue where users who just cloned the repo, and thus don't have the main branch locally (i.e. because the default branch is `beta`), are unable to create a changeset.
It's also the recommended approach according to the `changeset` documentation, which [Ernesto notes below](https://github.com/danstepanov/create-expo-stack/pull/79#issuecomment-1827605221)
Since this modifies the changeset configuration's baseBranch, it also affects the deployment process as outlined under the "Changes fro the Maintainer" heading.
Before, contributors would need to have the `main` branch available locally in order to run `bunx changeset`. This wasn't automatic, because `main` is not the default branch.
After this PR, contributors should already have the `beta` branch available locally because …
=> chore(changeset): baseBranch should the branch that PRs are based on / created against

.changeset/healthy-keys-help.md, cli/src/templates/packages/react-navigation/navigation/index.tsx.ejs
The Drawer Navigator template had a name mismatch in the RootStackParamList that caused TypeScript error on a newly created project using drawer navigator
I've replaced `TabNavigator` with `DrawerNavigator` in the type definition.
PS. This is my first contribution, please let me know if I forgot to do something
=> Fix incorrect type definition on DrawerNavigator template

.changeset/shy-drinks-sneeze.md, cli/src/templates/base/.gitignore.ejs
the .env file is created when firebase or supabase are used but it wasn't added to the .gitignore. This PR fixes that.
=> added .env to .gitignore when firebase or supabase is used

.changeset/small-penguins-dance.md, cli/src/commands/create-expo-stack.ts
Before, the CLI would exit with a status code of `0`, even if something went wrong, because we were catching any errors, logging a help message, and then letting the `src/commands/create-expo-stack.js` just return normally.
This meant that when a failure was caught and the command exited, things like tests wouldn't be aware that there was a failure at all, and would assume the test ran successfully.
This fixes the tests from passing when they shouldn't, and it also provides much better error diagnostics to the user for reporting purposes.
Here's a demonstration what happens when the CLI exits due to an error (specifically reproducing #136) before and after this change. Notice that my `%` zsh prompt is red in the "After", indicating the command failed, and the better diagnostic info + …
=> feat(commands): exit unsuccessfully with error, better error messages

.changeset/little-years-design.md, .changeset/silver-ears-lie.md, cli/src/commands/create-expo-stack.ts, cli/src/utilities/runCLI.ts, cli/src/utilities/validateProjectName.ts
Two fixes:
- related: #136.
Addressing the first bullet: here's the command stalling while running non-interactive (using `<$(mktemp)` to simulate non-interactive; using `</dev/null` crashes Bun); note the several empty newlines from pressing enter (to demonstrate that the shell is non-interactive / not accepting my input):
Addressing the second bullet: here's running the command twice, first without an existing `test/` and the second with one, on Linux; notice that I am not exiting the program, it just exits immediately upon the second prompt, i.e. the prompt immediately after `existsAsync`.
If the shell is non-interactive, we throw an error:
=> fix: stall in validateProjectName when non-interactive, unexpected exit when interactive

.changeset/light-bees-rush.md, cli/__tests__/cli-integration.test.ts, cli/src/commands/create-expo-stack.ts, cli/src/constants.ts, cli/src/types.ts, cli/src/utilities/runCLI.ts, cli/src/utilities/showHelp.ts
Since the addition of a prompt and/or error if the project directory already exists, tests are failing after the first project generation (or after previously running tests) because the test project directory already exists.
Tests are failing, either due to #136 or the fact that the directory already exists.
Tests are running (but still taking a while and may timeout in CI)
=> Fix test issues related to overwriting files

.changeset/loud-cheetahs-unite.md, cli/src/commands/create-expo-stack.ts
An exit with a ^C, ^D, etc. interrupt should exit successfully during the interactive CLI.
Exiting during the interactive CLI via ^C would output just `error` in red text along with the URL to submit issues (before #137), and now it outputs the full stack trace to the interrupt handler since the aforementioned PR was merged.
Catch the error as before but don't go through the normal error handling, instead wave goodbye:
Exiting the command during the actual build/running phase still results in an error (and still no error diagnostics), as you'd expect:
=> fix(commands): successfully exit when user cancels

.changeset/fast-fans-breathe.md, cli/src/commands/create-expo-stack.ts, cli/src/utilities/runCLI.ts, cli/src/utilities/runIgnite.ts
This refactor lays the groundwork for deleting the project folder if any error occurs while the CLI is running. It does this by determining & finalizing the project name before doing anything else within the command.
Two instances of asking the user and/or checking arguments for the project name have been "hoisted up" from `cli/src/utilities/runCLI` and `cli/src/utilities/runIgnite` into `cli/src/commands/create-expo-stack`, where we can now use the `projectName` in the last error handler for any purposes (such as deleting the generated project folder).
=> refactor(commands): get projectName before branching off into CLI

.changeset/shiny-eggs-peel.md, cli/src/templates/base/package.json.ejs
- Closes #143 
- Reports of yarn not working with `expo-router` templates specfically, `npm` and `bun` however were working fine.
- Related to locking the metro versions via resolutinos/overrides, taking that restriction off
=> fix(expo-router): yarn hot refresh

cli/src/commands/create-expo-stack.ts, docs/src/content/docs/en/installation.md
The `bun create` api requires mandatory destination path when including templates with options. You can check the docs [here](https://bun.sh/docs/cli/bun-create#from-npm) or see the screenshot
This PR clarifies the example chapter, making it specific to `npm`. Trying to replace `npm create` with `bun create` throws an error specific to bun api, since the destination for the template is not specified.
I'm not a bun superuser. Reading the docs made me think that I need to copy paste `bun create expo-stack` and then pass the options. The CLI will do the rest like asking the destination. Boy, was I wrong! Also, the `--bun` option is still required even thought you're using bun to create the project
Just run the command and add an option or two
`bun create expo-stack --expo-router`
=> Add scaffolding example with `bun create` 

cli/__tests__/cli-integration.test.ts, cli/package.json, cli/src/commands/create-expo-stack.ts
- Support kebab case for cli flags such as --no-install and --no-git
- Migrate tests to use kebab case, expand test coverage to ensure flags are working properly
- Do not include package manager in output non-interactive script if user is using npm
#150 
Run tests in cli
=> [cli] Support kebab case for cli flags

.husky/pre-commit
Previously, the pre-commit hook would ask the user if they wanted to created a changeset (i.e. run `bun run changeset`) if any files within `cli/` were modified, but it failed to include the changeset within the commit it ran against.
This resolves the issue and improves DX by automatically adding the newly created changeset to the commit during pre-commit.
Mentioned in the CES Discord, but I'm not seeing a related issue.
Although the previous behavior was "better than nothing" as it reminded the contributor to create a changeset file for them under the right circumstances, it's a clear flaw and quite misleading for the changeset made during the pre-commit hook to _not_ be included in the commit.
With this change, the creation **and inclusion** of changesets are automatic, avoiding any …
=> [infra] fix pre-commit not consuming created changeset

contributing.md
Contribution guidelines currently has no indication that external contributors should fork the repo instead of cloning directly from the source repository. This PR addresses that.
Additionally, it was noted that the content under the "Contribution Workflow" heading was getting too long without any descriptive lower level headings, so this PR also attempts to address that by breaking up this heading in the sections:
- Forking and cloning
- Directory structure
- Running the CLI from the global executable
- Making your changes
- #160
N/A
=> [docs] include instructions about forking in contribution guidelines

www/src/config.ts, www/src/pages/docs.astro
Navigating to createexpostack.com/docs reroutes to docs.createexpostack.com. Before it was showing a 404 page. 
For issue #172 
By putting  createexpostack.com/docs and seeing if it redirects to docs.createexpostack.com, and it did.
Before  
After
=> Rerouted createexpostack.com/docs to docs.createexpostack.com

.changeset/ninety-shoes-tan.md, cli/src/templates/base/package.json.ejs
tackling #176 by adding expo-modules-core@1.11.0 to the resolution/overrides in the package.json when using expo router
I can't really get to the source of the issue. somehow when initializing a project with expo-router it will fail with the error code  described in the issue. It is fixed by using the expo-modules-core v1.11. 
But I don't really understand why this is not a problem in every project using expo 49 and expo-router v2 because expo 49 has expo-modules-core@1.5 as a dependency and expo-router@2.0.0 (and all minor version above 2.0.0) raise the error.
Maybe someone else has some idea? 
#176
`bun run test --timeout=60000` in cli
`create-expo-stack my-expo-app --expo-router --nativewind`
`create-expo-stack my-expo-app --expo-router --stylesheet`
`create-expo-stack my-expo-app …
=> [cli] fix: added resolution/override for expo-modules-core to expo-router template

.changeset/nice-dragons-call.md, cli/src/commands/create-expo-stack.ts
- In an older Ignite version, only PascalCase project names were supported - that was enhanced with this Ignite PR: https://github.com/infinitered/ignite/pull/2534
- This PR removes that forced project name conversion
n/a
- Reduce code needed to maintain Ignite specifics
- More naming options for users
```
create-expo-stack ces-ignite --yarn
cd ces-ignite
yarn ios
```
=> [cli] fix: drop PascalCase req for ignite

cli/src/templates/packages/react-navigation/screens/home.tsx.ejs
When using nativewind, the home page will use `EditScreenInfo` but without its import
=> fix: missing import EditScreenInfo with nativewind config

docs/src/components/Header/MainNav.tsx, docs/src/consts.ts
In the docs, when you click Create Expo Stack, it goes back to the introduction page of the docs. But we want it to go back to the landing page. 
To give the user the ability to go back to the landing page from the docs. 
Simple change in the link href, tested manually.
=> [Docs] Made docs header logo navigate back to landing page

.changeset/small-ways-add.md, cli/src/templates/base/.gitignore.ejs
-  add ios and android folder to the gitignore folder
- follow continuous native generation principle : https://docs.expo.dev/workflow/continuous-native-generation/
=> [CLI] feat: add ios and android folder to the gitignore folder

.changeset/dull-socks-sing.md, cli/src/templates/base/package.json.ejs
Resolved:
```
✔ Created native directories
› Using current versions instead of recommended react-native@0.73.4.
```
can be reproduced with this command : 
`npx create-expo-stack project --unistyles --bun`
`cd project && bun expo prebuild --clean`
```
npx expo-doctor
Need to install the following packages:
expo-doctor@1.4.0
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match …
```
=> chore: bump react-native

cli/src/templates/base/package.json.ejs
Patch for the following error when we use bun / expo-router:
```
$ expo start --ios
Error: Cannot find module 'ajv/dist/compile/codegen'
```
To reproduce
`npx create-expo-stack@2.4.2 delete-create --expo-router --drawer+tabs --restyle --bun`
- https://github.com/expo/expo/issues/26641
- https://github.com/danstepanov/create-expo-stack/issues/204
=> [CLI] patch: bun + expo-router

.changeset/curly-coats-change.md, .changeset/gentle-games-rescue.md, .changeset/new-impalas-juggle.md, .gitignore, cli/README.md, cli/src/commands/create-expo-stack.ts, cli/src/templates/base/package.json.ejs, cli/src/utilities/getPackageManager.ts, cli/src/utilities/printOutput.ts, cli/src/utilities/runCLI.ts
=> Validate Bun Version

.changeset/happy-parrots-protect.md, cli/src/templates/base/package.json.ejs
`@react-native-async-storage/async-storage` has a strict peer dependency, i.e. a max version, of React Native it states it is compatible with. This isn't an issue for most package managers, just a warning, but for `npm >= 7` [peer dependencies are installed](https://stackoverflow.com/questions/66239691) and so their versions must match for the installation to succeed.
The newer version of `@react-native-async-storage/async-storage` recommended by the Expo CLI/bundler [updates the peer dependencies](https://github.com/react-native-async-storage/async-storage/pull/1029) and now allows any version of `react-native >=0.60 <1.0`, rather than setting a maximum version.
[`npm` issue posted in Discord](https://discord.com/channels/1173879003191459860/1181066944368103454/1224717782164439048)
`npm …
=> [cli] fix `npm >= 7` installation due to strict peer dependencies

.changeset/stale-eggs-yell.md, cli/src/templates/base/app.json.ejs
#update plugins condition in app.json.ejs
This pull request updates the plugins condition in `app.json.ejs` to avoid duplicated plugin keys in the final JSON output.
When generating the JSON output from `app.json.ejs`, it's important to ensure that there are no duplicated keys in the `plugins` section. This update addresses this issue by implementing some condition to avoid duplicated  `plugins`  key.
This change has been tested locally by updating `app.json.ejs` with the provided code changes and verifying that the JSON output does not contain duplicated plugin keys. Additionally, automated tests have been run to ensure that the code changes do not introduce any regressions.
=> update plugins condition in app.json.ejs

cli/src/templates/packages/nativewindui/components/ThemeToggle.tsx.ejs
Change a className to prevent the Android toggle theme icon from being cut off.
Not in this repo. Since it only removes 2 tailwind utility classes from an element and it was tested in another app, I did not rebuild and install a new project using the cli.
=> [cli] fix nativewind-ui android theme toggle icon from being cut off

cli/src/templates/base/package.json.ejs, cli/src/templates/base/tsconfig.json.ejs, cli/src/templates/packages/nativewindui/app/+not-found.tsx.ejs, cli/src/templates/packages/nativewindui/app/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/app/bottom-tabs/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/app/drawer/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/app/index.tsx.ejs, cli/src/templates/packages/nativewindui/app/modal.tsx.ejs, cli/src/templates/packages/nativewindui/app/top-tabs/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/app/top-tabs/following.tsx.ejs, cli/src/templates/packages/nativewindui/app/top-tabs/index.tsx.ejs, cli/src/templates/packages/nativewindui/app/top-tabs/my-group.tsx.ejs, cli/src/templates/packages/nativewindui/components/ThemeToggle.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/Text.tsx.ejs, cli/src/templates/packages/nativewindui/lib/useColorScheme.tsx.ejs, cli/src/templates/packages/nativewindui/lib/useHeaderSearchBar.tsx.ejs, cli/src/templates/packages/nativewindui/theme/colors.ts.ejs, cli/src/templates/packages/nativewindui/theme/index.ts.ejs, cli/src/utilities/configureProjectFiles.ts
- Centers the "empty list component" *
_*(**see recording below** as centering is tricky with a "largeTitle" in the header. It is completely centered when the search input is focused and a little higher than center otherwise. Of all the options, I think this one looks the best and it was the easiest to implement so that is looks good on all platforms and all devices.)_
- Replace `flatlist` with shopify's `flashlist`
- Change the typescript path alias to ‘~/‘ instead of ‘@/‘
- Update the color constant of "blue" to "primary" and "red" to "destructive"
For upcoming NativeWindUI template:
- Prevent the use of FlatList as there is no reason to use it anymore
- Use the default type alias used by recommended expo cli `npx create-expo-app@latest --template tabs@50`, other CES templates and …
=> [cli] nativewind-ui use flashlist + change ts path alias + update color const

cli/src/templates/base/app.json.ejs, cli/src/templates/base/package.json.ejs, cli/src/templates/packages/nativewindui/app/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/app/index.tsx.ejs, cli/src/templates/packages/nativewindui/app/modal.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/ActivityIndicator.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/DatePicker.android.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/Slider.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/Text.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/ThemeToggle.tsx.ejs, cli/src/templates/packages/nativewindui/components/nativewind-ui/Toggle.tsx.ejs, cli/src/templates/packages/nativewindui/global.css.ejs, cli/src/templates/packages/nativewindui/lib/useHeaderSearchBar.tsx.ejs, cli/src/types.ts, cli/src/utilities/runCLI.ts
- Fix wrong matching of color schemes by setting the userInterfaceStyle to automatic and changing color scheme with `setColorScheme` instead of `toggleColorScheme`. This led to issues like the wrong search bar color in the header.
- Change "actionnable-text" for "selectable-text"
- Only include `GestureHandlerRootView` with "bottom-sheet"
- Remove top-tab-navigation options
- Make settings page content similar to empty list content with non components selected
- Adjust empty list component to work for both ios and android in and do it in the same way.
- Fix color key "regression" ie: blue and red are now primary and destructive
- Fix android date picker import
- Only use `cssInterop` with uiTextView as it is not necessary for react-native's text component
- Fix an android css variable
- …
=> [cli] nativewind-ui adjustments

cli/src/templates/packages/nativewindui/app/index.tsx.ejs
- Fixes linter warnings `"x" is defined but never used` when certain components are not selected.
- Adds a comment for Android devices with the Store Review component as it has different conditions to be used than iOS.
Locally with bun on `iOS` and `android` devices for multiple different component selections.
=> [cli] fix nativewind-ui conditional imports + add android comment

cli/src/templates/packages/nativewindui/app/index.tsx.ejs
- Handle gracefully store review promise
- Show in console error 
-  show link to android conditions (for example, app needs to be at least in internal testing in play store to work)
- Prevent store review prompt from showing on every lazy load (scrolling far away then scrolling back to it). 
- Set the progress indicator to increase every second to prevent really fast progress increase randomly.
=> [cli] nw-ui/store-review handle error and show once + steady progress amount

cli/src/templates/packages/nativewindui/global.css.ejs
Update's the  the light mode `--android-muted-foreground` css variable.
Not tested with CES, only tested in main nativewind-ui project.
=> [cli] nw-ui update android css variable

www/src/components/landing/roadmap/roadmap.tsx, www/src/components/landing/terminal/terminal.astro, www/src/components/landing/testimonials/testimonials.tsx, www/src/styles/globals.css
- shiny animation was disabled as it consumed too much resources and slowed down other transitions on mobile
no padding on the terminal as you scroll to make it feel more real
before (with padding) gaps on the top & bottom and border radius cut-off
testimonials gap 2xl: before
testimonials gap 2xl after
roadmap before 
\
\
\
roadmap after
=> fix paddings and font sizes in multiple places to make it look nicer

cli/README.md
I came to CES hoping it to be on expo 51, I was confused it was still on 50 as I knew it is very active. I checked release history and realised it was on expo 51 but Readme just was not updated. 
Update Readme.md
=> Update README.md for Expo 51

.changeset/tiny-gorillas-add.md, cli/src/templates/packages/nativewindui/lib/useColorScheme.tsx.ejs
Makes the dark mode android navigation bar more transparent for NativeWindUI
The android navigation bar was more noticeable in dark mode than in light mode.
=> [cli] update dark android navigation bar color to match light mode

.changeset/tricky-students-sniff.md, cli/src/utilities/getPackageManager.ts, cli/src/utilities/runCLI.ts
At times the package manger wouldn't resolve correctly because neither the user agent or cli flag is set.
The issue was that the flag value was coming back undefined, I just double checked this and made the fallback more explicit.
We should always fallback to a valid option is not provided
yes locally
=> fix: correctly fallback to npm

.changeset/plenty-toys-pull.md, cli/src/utilities/printOutput.ts, cli/src/utilities/runEasConfigure.ts, cli/src/utilities/systemCommand.ts
If you try to run eas configure without running install it fails to find config plugins that its looking for, not to mention that running prebuild requires the packages to be installed.
Its a bad experience if we just let it fail with a cryptic message.
Ran locally.
=> feat: exit on no install eas

.changeset/gold-ads-shake.md, cli/src/templates/packages/expo-router/metro.config.js.ejs, cli/src/templates/packages/nativewindui/drawer/app/+not-found.tsx.ejs, cli/src/templates/packages/nativewindui/tabs/app/+not-found.tsx.ejs
Some `nativewind` code was added when it was not required. The bug was coming from a mistake in the if statement. :
```
<% if (props.stylingPackage?.name === "nativewind" || "nativewindui") { %>
```
In the following case, the if will always be "true" because `|| "nativewindui"` will always evaluate to true:
The fixed if statement is:
```
<% if (["nativewind", "nativewindui"].includes(props.stylingPackage?.name)) { %>
```
https://github.com/danstepanov/create-expo-stack/issues/318
- Created a new project with Expo router and without any nativewind, and it was fixed - the inport was not there, and the app runs correctly
- Created a new project with NativeWindUI and the imports where added correctly
=> [cli] Fix nativewind import when not required

www/demo/steps/printOutput.js
The _**website's**_ interactive CLI has separate code for the prompt + project's post-generation instructions, as it calls out to an API that actually generates the requested project. This PR updates the post-generation instructions to match the actual CLI for when `nativewindui` is selected, instructing the user to run `expo prebuild`.
N/A
Users who generate NativeWind UI projects need to run `expo prebuild` before their project will work.
N/A
N/A
=> [www] update website CLI to instruct to expo prebuild for NativeWindUI

.changeset/loud-geckos-leave.md, cli/src/templates/packages/tamagui/components/Button.tsx.ejs, cli/src/templates/packages/tamagui/tamagui.config.ts.ejs
The `components/Button` when using tamagui had wrong types. 
This pr:
- Changes the underlying component used for the tamagui button from `YStack` + `SizebleText` to `Button`
- Generates the styled button in `tamagui.config.js` when navigation is enabled, not only when using a Stack, because we generate the button component always, even if the Tabs and Drawer template are not using it. 
- Fixes custom button types `forwardRef<TamaguiElement, ButtonProps>`
- Custom button component now extends the types of the Tamagui Button
```
type ButtonProps = {
title: string;
} & ComponentProps<typeof TButton>;
```
- Sends the rest of tamagui button props down to the component `<TButton {...tButtonProps} ref={ref}>`
- This allows us to use the Custom Button with all available tamagui props. …
=> [cli] Fix tamagui button

.changeset/rich-bugs-tickle.md, cli/src/utilities/configureProjectFiles.ts
path was wrong for the not-found file
closes #342
fix the issue in #342
ran it locally
=> fix: notfound in wrong place #342

.changeset/grumpy-adults-trade.md, cli/src/commands/create-expo-stack.ts
- **fix: rerun script doesnt need expo router for NWUI**
Since expo router is added by default we can remove it from the rerun script
=> fix: rerun script doesnt need expo router for NWUI

.changeset/purple-ducks-sort.md, cli/src/templates/base/package.json.ejs
- **fix: missing dev launcher when using pnpm**
closes #372
pnpm wasn't resolving this peer dependency so adding it manually fixes this.
Ran locally and confirmed pnpm works after this change.
=> fix: eas should now work when pnpm is selected

www/src/components/landing/hero/copyCommandButton.tsx
The command copied to the clipboard does not include the `@latest` tag (while the code shown does)
This was missed on https://github.com/roninoss/create-expo-stack/commit/8b560e3d45502c6dbdbc4273ffaa82e198f71de0
=> fix: include `@latest` tag when copying the command

.changeset/smooth-gifts-lay.md, cli/__tests__/cli-integration.test.ts, cli/src/utilities/validateProjectName.ts
Just removes some unnecessary checks around the deletion that was stopping the user from being prompted when running in non-interactive mode. User can pass overwrite to skip the prompt.
closes #385 
#385
=> fix: should always prompt about deleting unless using --overwrite

.changeset/proud-humans-hug.md, cli/src/utilities/configureProjectFiles.ts
Nativewindui creates its own list of files separate from the base so npmrc wasn't getting added
I just moved it to the end so that its always applied when pnpm is used
=> fix: make sure npmrc gets added for pnpm

.changeset/twenty-chefs-burn.md, cli/src/commands/create-expo-stack.ts, cli/src/templates/base/package.json.ejs, cli/src/templates/packages/zustand/store/store.ts.ejs, cli/src/types.ts, cli/src/utilities/configureProjectFiles.ts, cli/src/utilities/generateProjectFiles.ts, cli/src/utilities/runCLI.ts, docs/src/content/docs/en/installation.md
I had added state management options to the ces flow
- Initially I have only added Zustand but with the approval of this PR I will look into adding other optons too
- Adds a question on the flow (see image) 
- Adds a --zustand flag to skip the question too.
This creates a folder in the root directory called state management with a default store from the zustand docs, it could be updated in future with a more generic store and some comments on how to use but to start with its the default store from zustand docs
My motivation was as I believe that ces can and should become one of the best and number one go to option for starting new RN expo apps and state management is mandatory in almost every app asit scales and having the setup from the get go is a must, as well as this the intuitive …
=> Adding State Management Options to CLI

.changeset/strong-pumpkins-exercise.md, cli/README.md, cli/__tests__/__snapshots__/cli-integration.test.ts.snap, cli/src/templates/base/components/Button.tsx.ejs, cli/src/templates/base/package.json.ejs, cli/src/templates/packages/nativewind/components/Button.tsx.ejs, cli/src/templates/packages/nativewindui/components/Button.tsx.ejs, cli/src/templates/packages/nativewindui/drawer/app/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/stack/app/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/tabs/app/_layout.tsx.ejs, cli/src/templates/packages/nativewindui/theme/index.ts.ejs, cli/src/templates/packages/restyle/components/Button.tsx.ejs, cli/src/templates/packages/unistyles/components/Button.tsx.ejs
I basically just updated the versions and then tried to fix the types that broke
Generated summary:
* Updated React Native to version 0.76 and React to version 18.3 in `cli/README.md` and `cli/src/templates/base/package.json.ejs`. [[1]](diffhunk://#diff-a60fd8fcc968f85dd50305193d1af8e94118afb7439f90c07bb434acd3490fabL62-R66) [[2]](diffhunk://#diff-87b23c3174a1077b26fad3f9cab0268cea77a905deac5cf02ecfd29031ef89f7L156-R167)
* Upgraded `expo` SDK to version 52 in `cli/README.md` and `cli/src/templates/base/package.json.ejs`. [[1]](diffhunk://#diff-a60fd8fcc968f85dd50305193d1af8e94118afb7439f90c07bb434acd3490fabL62-R66) [[2]](diffhunk://#diff-87b23c3174a1077b26fad3f9cab0268cea77a905deac5cf02ecfd29031ef89f7L156-R167)
* Updated `react-navigation` packages to the latest versions in …
=> fix: expo 52 and react navigation 7

.changeset/famous-ants-sell.md, cli/src/templates/packages/nativewindui/tailwind.config.js.ejs
Without this config, I get this error when trying to toggle darkmode in NativeWindUi in `Web` mode
```
Uncaught Error
Unable to manually set color scheme without using darkMode: class. See: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
```
steps to reproduce:
1.  npx create-expo-stack@latest
2. choose NativeWindUi
3. Try to toggle dark mode in `Web` mode
dark mode doesn't work without this change
Just tested that the toggle works
=> [cli] Update tailwind.config.js.ejs to enable manual toggle of dark mode

.changeset/cuddly-eagles-ring.md, cli/src/templates/base/tsconfig.json.ejs
A bunch of files that utilize Fragments (`<>`) don't import React which causes a TS error. This change adds those imports.
I ran `bun test` but it failed, send help.
=> add missing react import

.changeset/young-badgers-reply.md, cli/src/templates/base/package.json.ejs, cli/src/utilities/printOutput.ts
seeing some issues with peer deps when using npm, however it seems like the packages are in flux, the simplest thing is to just allow with legacy peer deps
=> fix: issues with npm peer deps

cli/src/templates/packages/nativewindui/components/EditScreenInfo.tsx.ejs, cli/src/templates/packages/nativewindui/components/ScreenContent.tsx.ejs
When building a project with the NativewindUI option, specifically using the expo-router with tabs for navigation, the text within both the Modal and Tab 2 screens does not update its styling when the theme (light/dark mode) is toggled.
Updating the ScreenContent.tsx.ejs and EditScreenInfo.tsx.ejs template files to import from the nativewindui component
[Issue-518](https://github.com/roninoss/create-expo-stack/issues/518)
This is a small tweak thats been bugging me since my first use of create-expo-app last year, and now I know enough to fix it for everyone <3
Its a very small change that uses the same coding patterns as other components within the template 
"worked in my local before I pushed to prod at 5am" - words of some ex-employee of some company
Screenshots before my fix are posted …
=>  [cli] fix: switching Text from react-native to nativewindui component in NativewindUI CLI Template
